Update setup.py
Hello, 

When I want to install hotspotd, an issue appears : 
File "/home/kali/Desktop/whatsapp/hotspotd-0.1.6/setup.py", line 13
    print 'Removing files from ' + loc
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Removing files from ' + loc)?

So I put for every print the parentheses. IDK if it would work.